### ISSUE TITLE
hstmIndexLibrary.cpp

### ISSUE THREAD

**Issue by impanyu** [michaelleerilee/hstm#1]
Hi, could you tell me where is hstmIndexLibrary.cpp and hstmIndexLibrary.h?

**Comment by michaelleerilee** [comment]
It's on the currently private repo michaelleerilee/SciDB-HSTM. I've sent an invitation. Please use the development branch.

**Comment by impanyu** [comment]
Thanks. And is there any relation between the repositories of
michaelleerilee/SciDB-HSTM and michaelleerilee/hstm?

Thanks,
Yu

**Comment by michaelleerilee** [comment]
SciDB-HSTM depends on hstm. It provides the shared object library that is loaded into SciDB, providing the UDOs and UDFs you call in queries.
As a note to the future, on a future release, we'll rename hstm to STARE.
Another repository 
michaelleerilee/SciDB-GridTransform
also depends on hstm. Michael Lee Rilee, Ph.D.Rilee Systems Technologies LLCContact: mike@rilee.net; Phone: 703-348-8127; Cell: 240-481-3254; Fax: 703-880-7202

**Comment by impanyu** [comment]
I see. Thanks for your explanation.

Thanks,
Yu

**Comment by michaelleerilee** [comment]
Anything else on this thread? If not, I'll close it.
